[2021-04-25 16:43:01,637: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 2.00 seconds... (1/100)

[2021-04-25 16:43:03,655: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2021-04-25 16:43:03,668: INFO/MainProcess] mingle: searching for neighbors
[2021-04-25 16:43:04,738: INFO/MainProcess] mingle: all alone
[2021-04-25 16:43:04,773: WARNING/MainProcess] /home/skydata/buy_it/env/lib/python3.8/site-packages/celery/fixups/django.py:205: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory
[2021-04-25 16:43:04,773: INFO/MainProcess] celery@skydata-Latitude-E5430-non-vPro ready.
[2021-04-25 17:33:16,110: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 599, in start
    c.loop(*c.loop_args())
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/worker/loops.py", line 83, in asynloop
    next(loop)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/kombu/asynchronous/hub.py", line 364, in create_loop
    cb(*cbargs)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/kombu/transport/base.py", line 238, in on_readable
    reader(loop)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/kombu/transport/base.py", line 220, in _read
    drain_events(timeout=0)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/amqp/connection.py", line 508, in drain_events
    while not self.blocking_read(timeout):
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/amqp/connection.py", line 514, in blocking_read
    return self.on_inbound_frame(frame)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/amqp/method_framing.py", line 55, in on_frame
    callback(channel, method_sig, buf, None)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/amqp/connection.py", line 520, in on_inbound_method
    return self.channels[channel_id].dispatch_method(
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/amqp/abstract_channel.py", line 145, in dispatch_method
    listener(*args)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/amqp/connection.py", line 649, in _on_close
    self._x_close_ok()
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/amqp/connection.py", line 664, in _x_close_ok
    self.send_method(spec.Connection.CloseOk, callback=self._on_close_ok)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/amqp/abstract_channel.py", line 59, in send_method
    conn.frame_writer(1, self.channel_id, sig, args, content)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/amqp/method_framing.py", line 189, in write_frame
    write(view[:offset])
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/amqp/transport.py", line 305, in write
    self._write(s)
ConnectionResetError: [Errno 104] Connection reset by peer
[2021-04-25 17:33:16,789: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 2.00 seconds... (1/100)


worker: Warm shutdown (MainProcess)
 
 -------------- celery@skydata-Latitude-E5430-non-vPro v4.4.7 (cliffs)
--- ***** ----- 
-- ******* ---- Linux-5.4.0-70-generic-x86_64-with-glibc2.29 2021-04-25 16:43:01
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         buy_it:0x7f012d5a1d90
- ** ---------- .> transport:   amqp://guest:**@localhost:5672//
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . orders.tasks.order_created

[2021-04-26 15:32:30,321: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2021-04-26 15:32:30,335: INFO/MainProcess] mingle: searching for neighbors
[2021-04-26 15:32:31,407: INFO/MainProcess] mingle: all alone
[2021-04-26 15:32:31,457: WARNING/MainProcess] /home/skydata/buy_it/env/lib/python3.8/site-packages/celery/fixups/django.py:205: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory
[2021-04-26 15:32:31,457: INFO/MainProcess] celery@skydata-Latitude-E5430-non-vPro ready.
[2021-04-26 16:45:30,472: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2021-04-26 16:45:30,487: INFO/MainProcess] mingle: searching for neighbors
[2021-04-26 16:45:31,559: INFO/MainProcess] mingle: all alone
[2021-04-26 16:45:31,602: WARNING/MainProcess] /home/skydata/buy_it/env/lib/python3.8/site-packages/celery/fixups/django.py:205: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory
[2021-04-26 16:45:31,602: INFO/MainProcess] celery@skydata-Latitude-E5430-non-vPro ready.
[2021-04-27 17:15:22,419: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2021-04-27 17:15:22,433: INFO/MainProcess] mingle: searching for neighbors
[2021-04-27 17:15:23,512: INFO/MainProcess] mingle: all alone
[2021-04-27 17:15:23,556: WARNING/MainProcess] /home/skydata/buy_it/env/lib/python3.8/site-packages/celery/fixups/django.py:205: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory
[2021-04-27 17:15:23,556: INFO/MainProcess] celery@skydata-Latitude-E5430-non-vPro ready.
[2021-04-28 22:58:24,570: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2021-04-28 22:58:24,582: INFO/MainProcess] mingle: searching for neighbors
[2021-04-28 22:58:25,658: INFO/MainProcess] mingle: all alone
[2021-04-28 22:58:25,740: WARNING/MainProcess] /home/skydata/buy_it/env/lib/python3.8/site-packages/celery/fixups/django.py:205: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory
[2021-04-28 22:58:25,740: INFO/MainProcess] celery@skydata-Latitude-E5430-non-vPro ready.

worker: Warm shutdown (MainProcess)
 
 -------------- celery@skydata-Latitude-E5430-non-vPro v4.4.7 (cliffs)
--- ***** ----- 
-- ******* ---- Linux-5.4.0-70-generic-x86_64-with-glibc2.29 2021-04-28 22:58:23
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         buy_it:0x7f3db02b2d90
- ** ---------- .> transport:   amqp://guest:**@localhost:5672//
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . orders.tasks.order_created

[2021-04-29 09:30:38,664: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2021-04-29 09:30:38,674: INFO/MainProcess] mingle: searching for neighbors
[2021-04-29 09:30:39,737: INFO/MainProcess] mingle: all alone
[2021-04-29 09:30:39,775: WARNING/MainProcess] /home/skydata/buy_it/env/lib/python3.8/site-packages/celery/fixups/django.py:205: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory
[2021-04-29 09:30:39,775: INFO/MainProcess] celery@skydata-Latitude-E5430-non-vPro ready.

worker: Warm shutdown (MainProcess)
 
 -------------- celery@skydata-Latitude-E5430-non-vPro v4.4.7 (cliffs)
--- ***** ----- 
-- ******* ---- Linux-5.4.0-70-generic-x86_64-with-glibc2.29 2021-04-29 09:30:38
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         buy_it:0x7f0017b91dc0
- ** ---------- .> transport:   amqp://guest:**@localhost:5672//
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . orders.tasks.order_created

[2021-04-29 16:18:45,925: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 2.00 seconds... (1/100)

[2021-04-29 16:18:47,942: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2021-04-29 16:18:47,956: INFO/MainProcess] mingle: searching for neighbors
[2021-04-29 16:18:49,018: INFO/MainProcess] mingle: all alone
[2021-04-29 16:18:49,056: WARNING/MainProcess] /home/skydata/buy_it/env/lib/python3.8/site-packages/celery/fixups/django.py:205: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory
[2021-04-29 16:18:49,056: INFO/MainProcess] celery@skydata-Latitude-E5430-non-vPro ready.
[2021-04-29 19:20:57,203: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 599, in start
    c.loop(*c.loop_args())
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/worker/loops.py", line 83, in asynloop
    next(loop)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/kombu/asynchronous/hub.py", line 364, in create_loop
    cb(*cbargs)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/kombu/transport/base.py", line 238, in on_readable
    reader(loop)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/kombu/transport/base.py", line 220, in _read
    drain_events(timeout=0)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/amqp/connection.py", line 508, in drain_events
    while not self.blocking_read(timeout):
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/amqp/connection.py", line 514, in blocking_read
    return self.on_inbound_frame(frame)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/amqp/method_framing.py", line 55, in on_frame
    callback(channel, method_sig, buf, None)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/amqp/connection.py", line 520, in on_inbound_method
    return self.channels[channel_id].dispatch_method(
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/amqp/abstract_channel.py", line 145, in dispatch_method
    listener(*args)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/amqp/connection.py", line 649, in _on_close
    self._x_close_ok()
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/amqp/connection.py", line 664, in _x_close_ok
    self.send_method(spec.Connection.CloseOk, callback=self._on_close_ok)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/amqp/abstract_channel.py", line 59, in send_method
    conn.frame_writer(1, self.channel_id, sig, args, content)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/amqp/method_framing.py", line 189, in write_frame
    write(view[:offset])
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/amqp/transport.py", line 305, in write
    self._write(s)
ConnectionResetError: [Errno 104] Connection reset by peer
[2021-04-29 19:20:58,030: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 2.00 seconds... (1/100)


worker: Warm shutdown (MainProcess)
 
 -------------- celery@skydata-Latitude-E5430-non-vPro v4.4.7 (cliffs)
--- ***** ----- 
-- ******* ---- Linux-5.4.0-70-generic-x86_64-with-glibc2.29 2021-04-29 16:18:45
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         buy_it:0x7f41d7d59d90
- ** ---------- .> transport:   amqp://guest:**@localhost:5672//
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . orders.tasks.order_created

[2021-04-29 22:36:45,727: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 2.00 seconds... (1/100)

[2021-04-29 22:36:47,751: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2021-04-29 22:36:47,766: INFO/MainProcess] mingle: searching for neighbors
[2021-04-29 22:36:48,836: INFO/MainProcess] mingle: all alone
[2021-04-29 22:36:48,870: WARNING/MainProcess] /home/skydata/buy_it/env/lib/python3.8/site-packages/celery/fixups/django.py:205: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory
[2021-04-29 22:36:48,870: INFO/MainProcess] celery@skydata-Latitude-E5430-non-vPro ready.
[2021-04-30 21:55:25,311: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 2.00 seconds... (1/100)

[2021-04-30 21:55:27,337: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2021-04-30 21:55:27,347: INFO/MainProcess] mingle: searching for neighbors
[2021-04-30 21:55:28,414: INFO/MainProcess] mingle: all alone
[2021-04-30 21:55:28,460: WARNING/MainProcess] /home/skydata/buy_it/env/lib/python3.8/site-packages/celery/fixups/django.py:205: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory
[2021-04-30 21:55:28,460: INFO/MainProcess] celery@skydata-Latitude-E5430-non-vPro ready.
[2021-05-01 11:47:03,735: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2021-05-01 11:47:03,750: INFO/MainProcess] mingle: searching for neighbors
[2021-05-01 11:47:04,825: INFO/MainProcess] mingle: all alone
[2021-05-01 11:47:04,890: WARNING/MainProcess] /home/skydata/buy_it/env/lib/python3.8/site-packages/celery/fixups/django.py:205: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory
[2021-05-01 11:47:04,891: INFO/MainProcess] celery@skydata-Latitude-E5430-non-vPro ready.
