Traceback (most recent call last):
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/kombu/transport/__init__.py", line 59, in resolve_transport
    transport = TRANSPORT_ALIASES[transport]
KeyError: 'ampq'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/skydata/buy_it/env/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/celery.py", line 499, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/base.py", line 305, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/celery.py", line 491, in handle_argv
    return self.execute(command, argv)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/celery.py", line 415, in execute
    return cls(
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/worker.py", line 223, in run_from_argv
    return self(*args, **options)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/base.py", line 253, in __call__
    ret = self.run(*args, **kwargs)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/worker.py", line 253, in run
    worker = self.app.Worker(
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/worker/worker.py", line 104, in __init__
    self.setup_instance(**self.prepare_args(**kwargs))
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/worker/worker.py", line 125, in setup_instance
    self._conninfo = self.app.connection_for_read()
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/app/base.py", line 761, in connection_for_read
    return self._connection(url or self.conf.broker_read_url, **kwargs)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/app/base.py", line 820, in _connection
    return self.amqp.Connection(
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/kombu/connection.py", line 189, in __init__
    if not get_transport_cls(transport).can_parse_url:
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/kombu/transport/__init__.py", line 87, in get_transport_cls
    _transport_cache[transport] = resolve_transport(transport)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/kombu/transport/__init__.py", line 65, in resolve_transport
    raise KeyError(
KeyError: 'No such transport: ampq.  Did you mean amqp?'
Traceback (most recent call last):
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/kombu/transport/__init__.py", line 59, in resolve_transport
    transport = TRANSPORT_ALIASES[transport]
KeyError: 'ampq'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/skydata/buy_it/env/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/celery.py", line 499, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/base.py", line 305, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/celery.py", line 491, in handle_argv
    return self.execute(command, argv)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/celery.py", line 415, in execute
    return cls(
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/worker.py", line 223, in run_from_argv
    return self(*args, **options)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/base.py", line 253, in __call__
    ret = self.run(*args, **kwargs)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/worker.py", line 253, in run
    worker = self.app.Worker(
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/worker/worker.py", line 104, in __init__
    self.setup_instance(**self.prepare_args(**kwargs))
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/worker/worker.py", line 125, in setup_instance
    self._conninfo = self.app.connection_for_read()
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/app/base.py", line 761, in connection_for_read
    return self._connection(url or self.conf.broker_read_url, **kwargs)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/app/base.py", line 820, in _connection
    return self.amqp.Connection(
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/kombu/connection.py", line 189, in __init__
    if not get_transport_cls(transport).can_parse_url:
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/kombu/transport/__init__.py", line 87, in get_transport_cls
    _transport_cache[transport] = resolve_transport(transport)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/kombu/transport/__init__.py", line 65, in resolve_transport
    raise KeyError(
KeyError: 'No such transport: ampq.  Did you mean amqp?'
Traceback (most recent call last):
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/kombu/transport/__init__.py", line 59, in resolve_transport
    transport = TRANSPORT_ALIASES[transport]
KeyError: 'ampq'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/skydata/buy_it/env/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/celery.py", line 499, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/base.py", line 305, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/celery.py", line 491, in handle_argv
    return self.execute(command, argv)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/celery.py", line 415, in execute
    return cls(
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/worker.py", line 223, in run_from_argv
    return self(*args, **options)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/base.py", line 253, in __call__
    ret = self.run(*args, **kwargs)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/worker.py", line 253, in run
    worker = self.app.Worker(
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/worker/worker.py", line 104, in __init__
    self.setup_instance(**self.prepare_args(**kwargs))
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/worker/worker.py", line 125, in setup_instance
    self._conninfo = self.app.connection_for_read()
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/app/base.py", line 761, in connection_for_read
    return self._connection(url or self.conf.broker_read_url, **kwargs)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/app/base.py", line 820, in _connection
    return self.amqp.Connection(
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/kombu/connection.py", line 189, in __init__
    if not get_transport_cls(transport).can_parse_url:
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/kombu/transport/__init__.py", line 87, in get_transport_cls
    _transport_cache[transport] = resolve_transport(transport)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/kombu/transport/__init__.py", line 65, in resolve_transport
    raise KeyError(
KeyError: 'No such transport: ampq.  Did you mean amqp?'
Traceback (most recent call last):
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/kombu/transport/__init__.py", line 59, in resolve_transport
    transport = TRANSPORT_ALIASES[transport]
KeyError: 'ampq'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/skydata/buy_it/env/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/celery.py", line 499, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/base.py", line 305, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/celery.py", line 491, in handle_argv
    return self.execute(command, argv)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/celery.py", line 415, in execute
    return cls(
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/worker.py", line 223, in run_from_argv
    return self(*args, **options)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/base.py", line 253, in __call__
    ret = self.run(*args, **kwargs)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/worker.py", line 253, in run
    worker = self.app.Worker(
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/worker/worker.py", line 104, in __init__
    self.setup_instance(**self.prepare_args(**kwargs))
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/worker/worker.py", line 125, in setup_instance
    self._conninfo = self.app.connection_for_read()
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/app/base.py", line 761, in connection_for_read
    return self._connection(url or self.conf.broker_read_url, **kwargs)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/app/base.py", line 820, in _connection
    return self.amqp.Connection(
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/kombu/connection.py", line 189, in __init__
    if not get_transport_cls(transport).can_parse_url:
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/kombu/transport/__init__.py", line 87, in get_transport_cls
    _transport_cache[transport] = resolve_transport(transport)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/kombu/transport/__init__.py", line 65, in resolve_transport
    raise KeyError(
KeyError: 'No such transport: ampq.  Did you mean amqp?'
Traceback (most recent call last):
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/kombu/transport/__init__.py", line 59, in resolve_transport
    transport = TRANSPORT_ALIASES[transport]
KeyError: 'ampq'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/skydata/buy_it/env/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/celery.py", line 499, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/base.py", line 305, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/celery.py", line 491, in handle_argv
    return self.execute(command, argv)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/celery.py", line 415, in execute
    return cls(
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/worker.py", line 223, in run_from_argv
    return self(*args, **options)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/base.py", line 253, in __call__
    ret = self.run(*args, **kwargs)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/worker.py", line 253, in run
    worker = self.app.Worker(
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/worker/worker.py", line 104, in __init__
    self.setup_instance(**self.prepare_args(**kwargs))
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/worker/worker.py", line 125, in setup_instance
    self._conninfo = self.app.connection_for_read()
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/app/base.py", line 761, in connection_for_read
    return self._connection(url or self.conf.broker_read_url, **kwargs)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/app/base.py", line 820, in _connection
    return self.amqp.Connection(
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/kombu/connection.py", line 189, in __init__
    if not get_transport_cls(transport).can_parse_url:
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/kombu/transport/__init__.py", line 87, in get_transport_cls
    _transport_cache[transport] = resolve_transport(transport)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/kombu/transport/__init__.py", line 65, in resolve_transport
    raise KeyError(
KeyError: 'No such transport: ampq.  Did you mean amqp?'
Traceback (most recent call last):
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/kombu/transport/__init__.py", line 59, in resolve_transport
    transport = TRANSPORT_ALIASES[transport]
KeyError: 'ampq'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/skydata/buy_it/env/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/celery.py", line 499, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/base.py", line 305, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/celery.py", line 491, in handle_argv
    return self.execute(command, argv)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/celery.py", line 415, in execute
    return cls(
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/worker.py", line 223, in run_from_argv
    return self(*args, **options)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/base.py", line 253, in __call__
    ret = self.run(*args, **kwargs)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/worker.py", line 253, in run
    worker = self.app.Worker(
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/worker/worker.py", line 104, in __init__
    self.setup_instance(**self.prepare_args(**kwargs))
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/worker/worker.py", line 125, in setup_instance
    self._conninfo = self.app.connection_for_read()
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/app/base.py", line 761, in connection_for_read
    return self._connection(url or self.conf.broker_read_url, **kwargs)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/app/base.py", line 820, in _connection
    return self.amqp.Connection(
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/kombu/connection.py", line 189, in __init__
    if not get_transport_cls(transport).can_parse_url:
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/kombu/transport/__init__.py", line 87, in get_transport_cls
    _transport_cache[transport] = resolve_transport(transport)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/kombu/transport/__init__.py", line 65, in resolve_transport
    raise KeyError(
KeyError: 'No such transport: ampq.  Did you mean amqp?'
Traceback (most recent call last):
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/kombu/transport/__init__.py", line 59, in resolve_transport
    transport = TRANSPORT_ALIASES[transport]
KeyError: 'ampq'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/skydata/buy_it/env/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/celery.py", line 499, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/base.py", line 305, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/celery.py", line 491, in handle_argv
    return self.execute(command, argv)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/celery.py", line 415, in execute
    return cls(
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/worker.py", line 223, in run_from_argv
    return self(*args, **options)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/base.py", line 253, in __call__
    ret = self.run(*args, **kwargs)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/worker.py", line 253, in run
    worker = self.app.Worker(
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/worker/worker.py", line 104, in __init__
    self.setup_instance(**self.prepare_args(**kwargs))
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/worker/worker.py", line 125, in setup_instance
    self._conninfo = self.app.connection_for_read()
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/app/base.py", line 761, in connection_for_read
    return self._connection(url or self.conf.broker_read_url, **kwargs)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/app/base.py", line 820, in _connection
    return self.amqp.Connection(
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/kombu/connection.py", line 189, in __init__
    if not get_transport_cls(transport).can_parse_url:
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/kombu/transport/__init__.py", line 87, in get_transport_cls
    _transport_cache[transport] = resolve_transport(transport)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/kombu/transport/__init__.py", line 65, in resolve_transport
    raise KeyError(
KeyError: 'No such transport: ampq.  Did you mean amqp?'
Traceback (most recent call last):
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/kombu/transport/__init__.py", line 59, in resolve_transport
    transport = TRANSPORT_ALIASES[transport]
KeyError: 'ampq'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/skydata/buy_it/env/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/celery.py", line 499, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/base.py", line 305, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/celery.py", line 491, in handle_argv
    return self.execute(command, argv)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/celery.py", line 415, in execute
    return cls(
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/worker.py", line 223, in run_from_argv
    return self(*args, **options)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/base.py", line 253, in __call__
    ret = self.run(*args, **kwargs)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/bin/worker.py", line 253, in run
    worker = self.app.Worker(
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/worker/worker.py", line 104, in __init__
    self.setup_instance(**self.prepare_args(**kwargs))
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/worker/worker.py", line 125, in setup_instance
    self._conninfo = self.app.connection_for_read()
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/app/base.py", line 761, in connection_for_read
    return self._connection(url or self.conf.broker_read_url, **kwargs)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/celery/app/base.py", line 820, in _connection
    return self.amqp.Connection(
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/kombu/connection.py", line 189, in __init__
    if not get_transport_cls(transport).can_parse_url:
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/kombu/transport/__init__.py", line 87, in get_transport_cls
    _transport_cache[transport] = resolve_transport(transport)
  File "/home/skydata/buy_it/env/lib/python3.8/site-packages/kombu/transport/__init__.py", line 65, in resolve_transport
    raise KeyError(
KeyError: 'No such transport: ampq.  Did you mean amqp?'
[2021-04-22 23:08:44,027: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2021-04-22 23:08:44,040: INFO/MainProcess] mingle: searching for neighbors
[2021-04-22 23:08:45,155: INFO/MainProcess] mingle: all alone
[2021-04-22 23:08:45,243: WARNING/MainProcess] /home/skydata/buy_it/env/lib/python3.8/site-packages/celery/fixups/django.py:205: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory
[2021-04-22 23:08:45,244: INFO/MainProcess] celery@skydata-Latitude-E5430-non-vPro ready.

worker: Warm shutdown (MainProcess)
 
 -------------- celery@skydata-Latitude-E5430-non-vPro v4.4.7 (cliffs)
--- ***** ----- 
-- ******* ---- Linux-5.4.0-70-generic-x86_64-with-glibc2.29 2021-04-22 23:08:43
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         buy_it:0x7fa44846dcd0
- ** ---------- .> transport:   amqp://guest:**@localhost:5672//
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . orders.tasks.order_created

[2021-04-23 11:53:30,528: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 2.00 seconds... (1/100)

[2021-04-23 11:53:32,548: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2021-04-23 11:53:32,561: INFO/MainProcess] mingle: searching for neighbors
[2021-04-23 11:53:33,624: INFO/MainProcess] mingle: all alone
[2021-04-23 11:53:33,682: WARNING/MainProcess] /home/skydata/buy_it/env/lib/python3.8/site-packages/celery/fixups/django.py:205: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory
[2021-04-23 11:53:33,682: INFO/MainProcess] celery@skydata-Latitude-E5430-non-vPro ready.
